-- Create public.collect_data table
create table if not exists public.collect_data (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  cabang text,
  
  -- Admin Cabang fields
  nama text,
  email text,
  tanggal_lahir date,
  no_hp text,
  nomor_kartu text,
  unit_bri text,
  promotor text,
  
  -- Layanan Konsumen / CS fields
  nama_cs text,
  tanggal_telepon date,
  jam_telepon time without time zone,
  plafon text,
  resep text,
  beli boolean,
  
  -- Staf Gudang fields
  nomor_acc_penjualan_silang text,
  nomor_sp text,
  alamat_pengiriman text,
  verifikasi_no_hp boolean,
  tanggal_kirim_frame date,
  actual text,
  tanggal_terima_frame date,
  sudah_terima_frame boolean,
  tanggal_kirim_lensa date,
  stock boolean,
  gosok boolean,
  acc_pusat_actual boolean,
  no_acc_pusat_actual text,
  no_faktur text,
  tanggal_terima_lensa date,
  sudah_produksi boolean,
  petugas_produksi text,
  tanggal_selesai_produksi date,
  
  -- Staf Keuangan Manajemen fields
  proses_pengiriman boolean,
  qc boolean,
  resi_pengiriman text,
  id_form text
);

-- Enable Row Level Security (RLS)
alter table public.collect_data enable row level security;

-- Drop existing policies if any
drop policy if exists "Enable SELECT access based on Role and Cabang" on public.collect_data;
drop policy if exists "Enable INSERT access for Admin Cabang" on public.collect_data;
drop policy if exists "Enable UPDATE access based on Role and Cabang" on public.collect_data;

-- Create SELECT Policy
create policy "Enable SELECT access based on Role and Cabang" 
on public.collect_data 
for select 
to authenticated 
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Staf Keuangan Manajemen', 'Staf Gudang')
  or 
  (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Admin Cabang', 'Layanan Konsumen')
    and 
    cabang = coalesce(auth.jwt() -> 'app_metadata' ->> 'cabang', auth.jwt() -> 'user_metadata' ->> 'cabang')
  )
);

-- Create INSERT Policy
create policy "Enable INSERT access for Admin Cabang" 
on public.collect_data 
for insert 
to authenticated 
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Staf Keuangan Manajemen', 'Staf Gudang')
  or
  (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin Cabang'
    and 
    cabang = coalesce(auth.jwt() -> 'app_metadata' ->> 'cabang', auth.jwt() -> 'user_metadata' ->> 'cabang')
  )
);

-- Create UPDATE Policy
create policy "Enable UPDATE access based on Role and Cabang" 
on public.collect_data 
for update 
to authenticated 
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Staf Keuangan Manajemen', 'Staf Gudang')
  or 
  (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Admin Cabang', 'Layanan Konsumen')
    and 
    cabang = coalesce(auth.jwt() -> 'app_metadata' ->> 'cabang', auth.jwt() -> 'user_metadata' ->> 'cabang')
  )
)
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Staf Keuangan Manajemen', 'Staf Gudang')
  or 
  (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('Admin Cabang', 'Layanan Konsumen')
    and 
    cabang = coalesce(auth.jwt() -> 'app_metadata' ->> 'cabang', auth.jwt() -> 'user_metadata' ->> 'cabang')
  )
);
